### ISSUE TITLE
Update guide after GE 2017.4 is out

### ISSUE THREAD

**Issue by lptr** [gradle-guides/using-build-cache#19]
We currently mention it as a future release:

https://github.com/gradle-guides/using-build-cache/blame/f900de3b176ae9a93b116744f8be355246e51142/contents/introduction.adoc#L35-L36

**Comment by wolfs** [comment]
We also should update the screenshots and add a screenshot for task origin.

**Comment by wolfs** [comment]
This has been fixed.
