### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by chaficnajjar** [gradle-guides/using-build-cache#23]
## Steps to reproduce

- `git clone git@github.com:gradle-guides/using-build-cache.git`
- `./gradlew build`

I'm running `./gradlew build` which should work according to the instructions at [_How do I build and serve all guides locally?_](https://github.com/gradle/guides#how-do-i-build-and-serve-all-guides-locally).

## Result

```
:gradleRunner
:asciidoctor
:compileJava NO-SOURCE
:compileGroovy NO-SOURCE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar
:assemble
:compileTestJava NO-SOURCE
:compileTestGroovy
:processTestResources NO-SOURCE
:testClasses
:test
:check
:build
:screenshots:compileJava NO-SOURCE
:screenshots:compileGroovy NO-SOURCE
:screenshots:processResources NO-SOURCE
:screenshots:classes UP-TO-DATE
:screenshots:jar
:screenshots:assemble
:screenshots:compileTestJava NO-SOURCE
:screenshots:compileTestGroovy
:screenshots:processTestResources
:screenshots:testClasses
:screenshots:downloadChromeDriver
:screenshots:unzipChromeDriver
:screenshots:test

TakeScreenshots > take_screenshots FAILED
    geb.waiting.WaitTimeoutException at TakeScreenshots.groovy:88

1 test completed, 1 failed
:screenshots:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':screenshots:test'.
> There were failing tests. See the report at: file:///home/chafic/desktop/guides/using-build-cache/screenshots/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 35s
11 actionable tasks: 11 executed
```

## Notes

I'm on Arch Linux.

**Comment by wolfs** [comment]
@chaficnajjar I think the right command should be `./gradlew :build` (note the `:`).

**Comment by wolfs** [comment]
The build cache guide is the only multi project build. I could also go ahead and try to remove the `:screenshots` tasks by default when executing `build`.

**Comment by chaficnajjar** [comment]
> @chaficnajjar I think the right command should be `./gradlew :build` (note the `:`).

@wolfs Thanks for this quick reply. This works.

> The build cache guide is the only multi project build.

What's important is for the instructions in [_How do I build and serve all guides locally?_](https://github.com/gradle/guides#how-do-i-build-and-serve-all-guides-locally) to work. The following command:

```
mr run ./gradlew build
```

...executes `./gradlew build` in each guide repository and fails in the `using-build-cache` directory.

> I could also go ahead and try to remove the `:screenshots` tasks by default when executing `build`.

I'm not familiar with how the Gradle build tool works or the importance of those tests so I prefer to leave this decision and the execution of this decision to you, @wolfs.

**Comment by wolfs** [comment]
@chaficnajjar Running `build` should work now. Could you please try it again?

**Comment by chaficnajjar** [comment]
@wolfs `./gradlew build` now works, thanks :smile:
